### ISSUE TITLE
PrimeVueResolver does not work well with Toast

### ISSUE THREAD

**Issue by ga676005** [antfu/unplugin-vue-components#132]
The component `<Toast />` works as intended if I imported it manually, but it does not appear after I added the `PrimeVueResolver` to the `resolver`. My other components work fine tho. I tried to solve the problem by removing `import Toast from 'primevue/toast'` and  `.component('Toast', Toast)` from my `main.js` but it does not help. It's probably an issue that needs to be looked into. Thank you.

Edit:
It seems to be only an issue during development because when I use `npm run build` and `npm run serve`, the toast component is working.

**Comment by gemone** [comment]
In my case, primevue's resolver is completely unavailable. PrimeVue version is `3.7.0`.

By checking the source code, it is found that there is a problem with `primevue's resolver`.

Lowercase is used as the folder name in the `primevue`, while uppercase is used in the `resolver`, which needs to be corrected here.

Just try to write others resolver.

The Original resolver: 

```ts
import { ComponentResolver, SideEffectsInfo } from '../../types'

const components = [
  'AutoComplete',
  'Calendar',
  'CascadeSelect',
  'Checkbox',
  'Chips',
  'ColorPicker',
  'Dropdown',
  'Editor',
  'InputMask',
  'InputNumber',
  'InputSwitch',
  'InputText',
  'Knob',
  'Listbox',
  'MultiSelect',
  'Password',
  'RadioButton',
  'Rating',
  'SelectButton',
  'Slider',
  'Textarea',
  'ToggleButton',
  'TreeSelect',
  'TriStateCheckbox',
  'Button',
  'SpeedDial',
  'SplitButton',
  'DataTable',
  'Column',
  'ColumnGroup',
  'DataView',
  'VirtualScroller',
  'FullCalendar',
  'OrderList',
  'OrganizationChart',
  'Paginator',
  'PickList',
  'Timelist',
  'Tree',
  'TreeTable',
  'Accordion',
  'AccordionTab',
  'Card',
  'DeferredContent',
  'Divider',
  'Fieldset',
  'Panel',
  'Splitter',
  'SplitterPanel',
  'ScrollPanel',
  'TabView',
  'TabPanel',
  'Toolbar',
  'ConfirmDialog',
  'ConfirmPopup',
  'Dialog',
  'OverlayPanel',
  'Sidebar',
  'Tooltip',
  'FileUpload',
  'Breadcrumb',
  'ContextMenu',
  'MegaMenu',
  'Menu',
  'Menubar',
  'PanelMenu',
  'Steps',
  'TabMenu',
  'TieredMenu',
  'Dock',
  'Chart',
  'Message',
  'Toast',
  'Carousel',
  'Galleria',
  'Image',
  'Avatar',
  'AvatarGroup',
  'Badge',
  'Chip',
  'BlockUI',
  'Inplace',
  'ScrollTop',
  'Skeleton',
  'ProgressBar',
  'ProgressSpiner',
  'Tag',
  'Terminal',
  'TerminalService',
]

export interface PrimeVueResolverOptions {
  /**
   * import style along with components
   *
   * @default true
   */
  importStyle?: boolean
  /**
   * import `primeicons' icons
   *
   * requires package `primeicons`
   *
   * @default true
   */
  importIcons?: boolean
  /**
   * imports a free theme - set theme name here (e.g. saga-blue)
   *
   * @default ''
   */
  importTheme?: string
}

/**
 * Resolver for PrimeVue - If you're using a component with the same tag as an native HTML element (e.g. button) the component must be in uppercase
 *
 * @link https://github.com/primefaces/primevue
 */
export function PrimeVueResolver(options: PrimeVueResolverOptions = {}): ComponentResolver {
  return (name: string) => {
    const sideEffects: SideEffectsInfo = []

    if (options.importStyle)
      sideEffects.push('primevue/resources/primevue.min.css')

    if (options.importIcons)
      sideEffects.push('primeicons/primeicons.css')

    if (options.importTheme) {
      sideEffects.push(
        `primevue/resources/themes/${options.importTheme}/theme.css`,
      )
    }

    if (components.includes(name)) {
      return {
        path: `primevue/${name}/${name}.vue`,
        sideEffects,
      }
    }
  }
}
```

Should be: 

```ts
// ...
    if (components.includes(name)) {
      return {
        path: `primevue/${name.toLowerCase()}/${name}.vue`,
        sideEffects,
      }
   }

// ...
```

Just modify the 'path' line: 

```ts
path: `primevue/${name}/${name}.vue`,
```

to:

```ts
path: `primevue/${name.toLowerCase()}/${name}.vue`,
```

It should fix it.

When I'm free, I'll PR. 

You can submit it if it is convenient for you.

**Comment by ga676005** [comment]
Before the patch, my primevue components are already working. After updating the package, The toast component is still having the same issue which doesn't not appear in `npm run dev`, but functional in `npm run build` then `npm run serve`. Since `import ToastService from 'primevue/toastservice' and `createApp(APP).use(ToastService)` are necessary to make the toast component work, maybe exclude the toast component from the list, so manually import toast component `import Toast from 'primevue/toast'` and `createApp(APP).component('Toast', Toast)` would work.
